### ISSUE TITLE
`jr update-manifest ...` was broken by octokit update to v16.x

### ISSUE THREAD

**Issue by trentm** [joyent/joyent-repos#8]
#### Problem 1: method deprecation

```
$ jr -v update-manifest tools/jr-manifest.json 2> >(bunyan)
...
[2019-10-24T21:46:59.343Z] TRACE: jr/1307 on bluesteel.local (/Users/trentm/joy/joyent-repos/lib/cli/do_update_manifest.js:45 in iteration): octokit paginated call: iteration (octokitMethodName=repos.getForOrg)
    reqOpts: {
      "per_page": 100,
      "org": "joyent",
      "type": "public"
    }
/Users/trentm/joy/joyent-repos/lib/cli/do_update_manifest.js:58
                jsprim.pluck(opts.octokit, opts.methodName)(reqOpts, onRes);
                                                           ^

TypeError: jsprim.pluck(...) is not a function
    at iteration (/Users/trentm/joy/joyent-repos/lib/cli/do_update_manifest.js:58:60)
    at Immediate.iterate (/Users/trentm/joy/joyent-repos/node_modules/vasync/lib/vasync.js:380:3)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
```

Octokit/rest.js update from 15.x to 16.x [includes](https://github.com/octokit/rest.js/releases/tag/v16.0.1):

> all [previously deprecated methods](https://github.com/octokit/rest.js/releases/tag/v15.18.0#deprecations) have been removed

including the "repos.getForOrg" that we are using.

**Comment by trentm** [comment]
#### Problem 2: callback-based usage of octokit/rest.js is dead

```
$ jr -v update-manifest tools/jr-manifest.json 2> >(bunyan)
[2019-10-24T21:50:31.042Z] TRACE: jr/1410 on bluesteel.local (/Users/trentm/joy/joyent-repos/lib/cli/index.js:160 in init): manifestPaths
    manifestPaths: [
      "/Users/trentm/all/triton/tools/jr-manifest.json",
      "/Users/trentm/all/triton-dev/jr-manifest.json",
      "/Users/trentm/all/manta/tools/jr-manifest.json",
      "/Users/trentm/all/smartos-live/tools/jr-manifest.json",
      "/Users/trentm/joy/play/jr-manifest.json"
    ]
Gathering candidate repos from GitHub.
[2019-10-24T21:50:31.061Z] TRACE: jr/1410 on bluesteel.local (/Users/trentm/joy/joyent-repos/lib/cli/do_update_manifest.js:39 in test): octokit paginated call: test (octokitMethodName=repos.listForOrg, more=true)
    reqOpts: {
      "per_page": 100,
      "org": "joyent",
      "type": "public"
    }
[2019-10-24T21:50:31.061Z] TRACE: jr/1410 on bluesteel.local (/Users/trentm/joy/joyent-repos/lib/cli/do_update_manifest.js:46 in iteration): octokit paginated call: iteration (octokitMethodName=repos.listForOrg)
    reqOpts: {
      "per_page": 100,
      "org": "joyent",
      "type": "public"
    }
```

That just ends there.   No mention I see in the changelog about this change. Lovely. Hooray for promises.
